## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.
version: 0.4.0.0

run-mode: replace

source-paths:
  - cascade-prelude/src
  - cascade-api/src
  - cascade-api/test
  - cascade-api/benchmark
  - cascade-cli/app
  - cascade-cli/src
  - cascade-cli/test

excluded-paths:
  - Setup.hs

template-paths:
  - .headroom-templates

variables:
  project: Cascade
  year: "2020"
  maintainer_name: Mohammad Hasani
  maintainer_email: the-dr-lazy@pm.me
  maintainer_comment: the-dr-lazy.github.io

license-headers:
  haskell:
    put-before: ["^module"]
    margin-top-code: 1
    margin-bottom-code: 1
    margin-bottom-file: 1

post-process:
  update-copyright:
    enabled: true
