#!/bin/bash

set -e

output=$(realpath -m ./coverage/reports)

rm -rf $output
mkdir -p $output

packages=(
	"cascade-api"
	"cascade-prelude"
)
configuration=$(cat cabal.project.local 2>&1 || echo "")
exitcode=1

for package in "${packages[@]}"; do
	cat <<EOF >cabal.project.local
$configuration

package $package
  coverage: True
  library-coverage: True
EOF

	cd $package

	if cabal new-build "$package-test" && cabal new-test "$package-test"; then
		tix=$(find ../dist-newstyle -name $package-*.*.tix)

		mixes=""
		for mix in $(find ../dist-newstyle -path "*vanilla/mix/$package*" -type d -print); do
			mixes+="--mix $mix "
		done

		hpc-codecov $mixes --out=$output/$package.json $tix
	else
		exitcode=1
	fi

	cd ..
	cat <<EOF >cabal.project.local
$configuration
EOF
done

exit $exitcode
