name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: cascade
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Cache ~/.cabal/store
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-build-${{ hashFiles('shell.nix', 'cabal.project', 'cabal.project.freeze', 'cabal.project.local') }}
      - name: Bootstrap
        run: |
          nix develop -c ./scripts/bootstrap.sh
          nix develop -c cabal update
          nix develop -c cabal new-configure --disable-documentation \
                                             --disable-optimization \
                                             --enable-tests \
                                             --enable-benchmarks \
                                             --disable-coverage \
                                             --test-show-details=direct"
      - name: Build
        run: nix develop -c cabal build all
      - name: Cache ~/.cascade/tmp-postgres
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cascade/tmp-postgres
          key: ${{ runner.os }}-test-${{ hashFiles('migrations/**/*') }}
      - name: Test
        run: nix develop -c cabal test all
