name: CI

on:
  pull_request:
    branches:
      - next
      - master
  push:
    branches:
      - next
      - master

jobs:
  workflow:
    name: Workflow
    # Ubuntu builds disabled due to issue with installing libjwt-dev@1.12.x
    # ToDo: enable it when it's possible to install the library
    runs-on: macOS-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        id: haskell
        with:
          ghc-version: "8.8.4"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache ~/.cabal/store
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.haskell.outputs.cabal-store }}
          key: build-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}-${{ hashFiles('cabal.project.freeze') }}-${{ hashFiles('cabal.project.local') }}

      - name: Install OS Packages
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1

          brew install libjwt

          echo "~/.cabal/bin" >> $GITHUB_PATH

          OS_CABAL_TEMP_DIR=$(mktemp -d -t .os-cabal-XXXXX)
          cp cabal.project.freeze $OS_CABAL_TEMP_DIR
          (cd $OS_CABAL_TEMP_DIR && cabal init --non-interactive && cabal new-install hpack-dhall)

          dhall-hpack-cabal --version

      - name: Configure
        run: |
          ./scripts/cabal
          cabal new-configure --disable-documentation \
                              --disable-optimization \
                              --enable-tests \
                              --enable-benchmarks \
                              --disable-coverage \
                              --test-show-details=direct

      - name: Install Dependencies
        run: |
          cabal new-build all --only-dependencies

      - name: Build
        run: |
          cabal new-build all

      - name: Install OS Packages
        run: |
          brew install coreutils postgres

          brew tap sqitchers/sqitch
          brew install sqitch --with-postgres-support

          postgres --version
          sqitch --version

      - name: Cache ~/.cascade/tmp-postgres
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cascade/tmp-postgres
          key: test-${{ runner.os }}-${{ hashFiles('migrations/**/*') }}

      - name: Test
        run: |
          cabal new-test all
