name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - next

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: haskell
        with:
          ghc-version: "8.8.4"
          cabal-version: "3.2"

      - name: Configure
        run: |
          cabal new-configure --enable-tests --enable-benchmarks --test-show-details=direct

      - uses: actions/cache@v2.1.3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal new-build all --only-dependencies
          cabal new-install tasty-discover

      - name: Build
        run: |
          cabal new-build all

      - uses: actions/cache@v2.1.3
        name: Cache ~/.cascade/tmp-postgres
        with:
          path: ~/.cascade/tmp-postgres
          key: ${{ runner.os }}-${{ hashFiles('migrations/sqitch.plan') }}

      - name: Install Sqitch
        uses: knicknic/os-specific-run@v1.0.2
        with:
          linux: |
            sudo apt-get install sqitch libdbd-pg-perl postgresql-client
          macos: |
            brew tap sqitchers/sqitch
            brew install sqitch --with-postgres-support --with-sqlite-support

      - name: Install PostgreSQL
        uses: knicknic/os-specific-run@v1.0.2
        with:
          linux: |
            sudo apt-get install postgresql-13
            echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH
            postgres --version
          macos: |
            brew install postgres
            postgres --version

      - name: Test
        run: |
          cabal new-test all
