name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-haskell@v1.1
        id: setup-haskell
        with:
          ghc-version: "8.8.4"
          cabal-version: "3.2"

      - name: Configure
        run: |
          cabal new-configure --enable-tests --enable-benchmarks --test-show-details=direct

      - uses: actions/cache@v2.1.3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies

      - name: Build
        run: |
          cabal build all

      - name: Test
        run: |
          cabal test all
