name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - next

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: haskell
        with:
          ghc-version: "8.8.4"
          cabal-version: "3.2"

      - name: Configure
        run: |
          cabal new-configure --enable-tests --enable-benchmarks --test-show-details=direct

      - uses: actions/cache@v2.1.3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal new-build all --only-dependencies
          cabal new-install tasty-discover

      - name: Build
        run: |
          cabal new-build all

      - name: Test
        run: |
          cabal new-test all
