name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - next

jobs:
  headroom:
    name: Headroom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Headroom
        run: |
          sudo curl -Lo /usr/bin/headroom https://github.com/vaclavsvejcar/headroom/releases/download/v0.3.2.0/headroom-0.3.2.0-Linux-ghc-8.8.4
          sudo chmod +x /usr/bin/headroom

      - name: Check headers
        run: headroom run --check-headers

  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: haskell
        with:
          ghc-version: "8.8.4"
          cabal-version: "3.2"

      - name: Configure
        run: |
          cabal new-configure --disable-optimization --enable-tests --enable-benchmarks --test-show-details=direct

      - uses: actions/cache@v2.1.3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.haskell.outputs.cabal-store }}
          key: build-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal new-build all --only-dependencies

      - name: Build
        run: |
          cabal new-build all

  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO: running tests on Ubuntu
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: haskell
        with:
          ghc-version: "8.8.4"
          cabal-version: "3.2"

      - name: Setup environment
        uses: knicknic/os-specific-run@v1.0.2
        with:
          linux: |
            sudo apt-get update
            sudo apt-get --yes remove postgresql\*
            sudo apt-get --yes install postgresql-13
            sudo service postgresql restart 13
            echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH
            export PATH=/usr/lib/postgresql/13/bin:$PATH

            sudo apt-get --yes install sqitch libdbd-pg-perl postgresql-client-13

            postgres --version
          macos: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            export HOMEBREW_NO_INSTALL_CLEANUP=1

            brew install coreutils
            brew install postgres

            brew tap sqitchers/sqitch
            brew install sqitch --with-postgres-support

            postgres --version

      - name: Setup $PATH
        run: |
          echo "~/.cabal/bin" >> $GITHUB_PATH

      - name: Configure
        run: |
          cabal new-configure --enable-optimization=2 --enable-tests --enable-coverage --test-show-details=direct

      - name: Cache ~/.cabal/store
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.haskell.outputs.cabal-store }}
          key: test-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal new-build all --only-dependencies
          cabal new-install hpc-codecov --install-method=copy --overwrite-policy=always

      - name: Cache ~/.cascade/tmp-postgres
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cascade/tmp-postgres
          key: test-${{ runner.os }}-${{ hashFiles('migrations/sqitch.plan') }}

      - name: Build
        run: |
          cabal new-build all

      - name: Test
        run: |
          cabal new-test all

      - name: Generate coverage reports
        run: |
          scripts/codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: Cascade
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "*.json"
          directory: ./coverage/reports
          fail_ci_if_error: true
          verbose: true
